### ISSUE TITLE
More detail on commit message titles

### ISSUE THREAD

**Issue by dgmstuart** [dxw/playbook#33]
https://github.com/dxw/playbook/blob/master/playbook.md#committing

The only instructions on commit titles are: 
"Messages should convey in the present tense what the new state of the system will be"

I feel like this needs a little fleshing out, maybe a few more examples.

cc @tahb

**Comment by harry-m** [comment]
Would be good to talk about this when you have a minute - did you have any specific questions or things you were unsure about?

**Comment by dgmstuart** [comment]
@harry-m personally I know what it means, but I think it needs a few more examples in order to be actually useful to new people.

**Comment by harry-m** [comment]
OK. Can anyone else pitch in with some feedback on this section? What would make it clearer?

**Comment by tomdxw** [comment]
It may be more accurate to say "use the imperative mood" than "use the present tense". Several pieces of git advice use that term ([1](http://chris.beams.io/posts/git-commit/#imperative), [2](https://github.com/erlang/otp/wiki/Writing-good-commit-messages), [3](https://git-scm.com/book/ch5-2.html)).

[This one](https://github.com/erlang/otp/wiki/Writing-good-commit-messages) has some concrete examples:

> Write the summary line and description of what you have done in the imperative mode, that is as if you were commanding someone. Start the line with "Fix", "Add", "Change" instead of "Fixed", "Added", "Changed".

Is that the sort of thing you were thinking about, @dgmstuart ?

**Comment by dgmstuart** [comment]
Nope - using the imperative is a different style to using the present tense: the former talks about what dev work was done, the latter talks about what behaviour is present after the change. 

Happy to consider settling on either as a convention. Will try and dig out the blog post that prompted the "present tense" form

**Comment by tahb** [comment]
I much prefer present tense as it is much more useful to describe what the system now does instead of what action has been taken, which could leave the new behaviour open to interpretation.

If I want to understand a commit or revert a commit, I want to be confident in the behaviour that will be added or removed. Knowing that a 'payment form was fixed' gives me no confidence.

We include the prefixes: (feature), (fix), (refactor), (chore) to convey the general type of the commit which I think works well. https://github.com/dxw/playbook/blob/master/playbook.md#committing

I'm happy to flesh this area out a little more when I can find the time.

**Comment by harry-m** [comment]
Ok. I think it is agreed that:

* Commit messages will describe the new state in the present tense
* That this could use slightly more explanation (but really only slightly)
* That another example would be helpful

@tahb I'll assign this to you now, to do when you get to it.

**Comment by techbelly** [comment]
No interest in re-opening this grammatical third rail, but looking at the repos, in mytvh we seem to be largely settled on using the imperative present (though there's some inconsistency), eg. :

  'Bump internal gem to v1.15.0'
  'Merge StoreContactDetailWorker into UpdatePersonWorker'
  'Show a message for no matching locations'

In, say, the judiciary theme, there's some indicative present:
  'Useful links point to correct place'
And some past tense:
  'Fixed PHP errors'
  'Updated compose and vendor'

I'm sure I can see examples of all moods/styles/tenses in all our recent code.

The imperative mood/present tense split is a red herring. 

What we really want to say is write commit messages in the present tense, use the imperative mood but avoid talking from the perspective of the coder or the code. So...

I. 'Show a message to users when...' is good (imperative mood, present tense),
II. 'Shows a message to users when...' is not so good? (indicative mood, present tense),

III. 'Add feature to show message' is not so good (imperative mood, present tense, but from perspective of code not feature),
IV. 'Adds feature to show message' not so good (present tense, indicative mood, from perspective of code)
V. 'Added feature to show message' not so good (using past tense, indicative mood)

The tense, mood thing is hard and unfamiliar for most people, for that reason I tend to prefer II above (indicative, present) because it's easy to coach as: imagine your commit message begins 'adding this commit changes the application so that it ...' 

People do tend to prefer I for convention sake and consistency with tooling. For example, when git makes a Merge commit it uses imperative present. It feels like we most commonly use it?

It does feel like it's worth being a bit more consistent about this.

I'm happy to come up with some examples, can I take this from you @tabh and get it to closed?

**Comment by dgmstuart** [comment]
@techbelly would be great to have some examples when you get a chance. 

My education in grammar was sorely lacking

**Comment by CristinaRO** [comment]
There are examples now https://playbook.dxw.com/guides/development-workflow.html#committing. We could add more detail about the intent of commit messages, and some links to blog posts or talks, but this issue can be considered fixed.

**Comment by tahb** [comment]
Crumbs I didn't realise I was still assigned to this, it was evidently not on my radar even after 4 years passed. Thank you for coming through and closing it @CristinaRO 🙌 

[A pull request with more examples](https://github.com/dxw/playbook/pull/58/files#diff-130a25509cabf8968453f8d2084cbf91R268) _was_ merged in back in Nov 2016! :tada: It appears I forgot to come back to this issue and seek to close this issue after it was merged. Better late than never?
